# Generated by Django 6.0.3 on 2026-04-15 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_branch_gstin_alter_branch_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_agents', to='branches.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Agent',
                'verbose_name_plural': 'Loan Agents',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='LoanCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('id_proof_type', models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('voter', 'Voter ID'), ('passport', 'Passport'), ('driving_license', 'Driving License')], max_length=30)),
                ('id_proof_number', models.CharField(blank=True, max_length=50)),
                ('id_proof_document', models.FileField(blank=True, null=True, upload_to='loan_kyc/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='loan_customer_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('blacklisted', models.BooleanField(default=False)),
                ('blacklist_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='loan_customers.loanagent')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_customers', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_customers_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Customer',
                'verbose_name_plural': 'Loan Customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
