# Generated by Django 6.0.3 on 2026-04-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loancustomer',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='loancustomer',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='loancustomer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loancustomer',
            name='user',
        ),
    ]
