# Generated by Django 6.0.3 on 2026-04-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_customers', '0002_remove_loancustomer_agent_remove_loancustomer_branch_and_more'),
        ('loans', '0002_alter_loan_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanCustomer',
        ),
    ]
