# Generated by Django 6.0.3 on 2026-04-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitgroup',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
