# Generated by manual addition for penalty features
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('chits', '0003_chitgroup_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitgroup',
            name='due_day',
            field=models.IntegerField(default=10, help_text='Monthly installment due day (e.g., 10th of every month)'),
        ),
        migrations.AddField(
            model_name='chitgroup',
            name='penalty_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty amount to be charged per day after the due date', max_digits=10),
        ),
    ]
