# Generated by Django 6.0.3 on 2026-04-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chits', '0004_penalty_fields'),
        ('members', '0004_member_branch_and_nominee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitgroup',
            name='members',
            field=models.ManyToManyField(related_name='chit_groups', through='chits.ChitMember', to='members.member'),
        ),
    ]
