# Generated by Django 6.0.3 on 2026-04-15 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan_payments', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='emi_installment',
            field=models.ForeignKey(blank=True, help_text='The specific EMI instalment this payment is against.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='loans.emischedule'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loanpayment_set', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan_payments.loanpayment'),
        ),
    ]
