# Generated by Django 6.0.3 on 2026-04-17 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_payments', '0002_initial'),
        ('loans', '0003_loan_loan_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('screenshot', models.ImageField(upload_to='loan_payment_proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from the admin/staff', null=True)),
                ('member_notes', models.TextField(blank=True, help_text='Notes from the customer', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('emi_installment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='loans.emischedule')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_loan_proofs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
