# Generated by Django 6.0.3 on 2026-04-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_payments', '0003_loanpaymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpaymentproof',
            name='member_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanpaymentproof',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
