# Generated by Django 6.0.3 on 2026-03-31 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chits', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.IntegerField()),
                ('auction_date', models.DateField()),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chit_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chits.chitgroup')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_auctions', to='members.member')),
            ],
            options={
                'unique_together': {('chit_group', 'month_number')},
            },
        ),
    ]
