# Generated by Django 6.0.3 on 2026-04-15 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('members', '0005_rename_address_member_blacklist_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_set', to='members.member'),
        ),
    ]
