# Generated by Django 6.0.3 on 2026-04-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'Personal Loan'), ('home', 'Home Loan'), ('gold', 'Gold Loan'), ('vehicle', 'Vehicle Loan'), ('property', 'Property Loan'), ('business', 'Business Loan'), ('education', 'Education Loan'), ('other', 'Other')], default='personal', help_text='Select the category of loan', max_length=20),
        ),
    ]
