# Generated by Django 6.0.3 on 2026-04-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_account_number_member_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdocument',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Reason for rejection or verification notes', null=True),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved (Verified)'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='document_type',
            field=models.CharField(choices=[('AADHAR', 'Aadhar Card'), ('PAN', 'PAN Card'), ('VOTER', 'Voter ID'), ('DRIVING', 'Driving License'), ('BANK', 'Bank Passbook'), ('OTHER', 'Other Document')], max_length=20),
        ),
    ]
