# Generated by Django 6.0.3 on 2026-04-15 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_customers', '0002_remove_loancustomer_agent_remove_loancustomer_branch_and_more'),
        ('members', '0004_member_branch_and_nominee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.AddField(
            model_name='member',
            name='blacklist_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='id_card_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Type'),
        ),
        migrations.AddField(
            model_name='member',
            name='id_proof_document',
            field=models.FileField(blank=True, null=True, upload_to='members/id_proofs/'),
        ),
        migrations.AddField(
            model_name='member',
            name='loan_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to='loan_customers.loanagent'),
        ),
        migrations.AddField(
            model_name='member',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.CharField(default='Tamil Nadu', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Aadhar/PAN Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
